#!/bin/sh

cd ~
curl --remote-name https://raw.githubusercontent.com/wherebyus/laptop/master/mac
curl --remote-name https://raw.githubusercontent.com/wherebyus/laptop/master/Brewfile
/usr/bin/env bash mac 2>&1 | tee ~/laptop.log
